const crypto = require('crypto');

/**
 *  Building the signing based on prerequest script seen on Aquanow's own Postman collection:
 *   signatureContent = JSON.stringify({ httpMethod, path, nonce })
      which excludes the query string.)
 */
function buildSignatureContent({ httpMethod, path, nonce }) {
  return JSON.stringify({ httpMethod, path, nonce });
}

/**
 * HMAC-SHA384 over the signature content, keyed by the API secret, hex digest.
 * (Aquanow is using SHA384 — note: NOT SHA256 — matching CryptoJS.HmacSHA384 in
 * their pre-request script.)
 */
function signRequest({ apiSecret, httpMethod, path, nonce }) {
  const signatureContent = buildSignatureContent({ httpMethod, path, nonce });
  return crypto.createHmac('sha384', apiSecret).update(signatureContent).digest('hex');
}

//  each request is signed with the signature generated by this function, 
module.exports = { buildSignatureContent, signRequest };